- name: Configure ClickHouse Servers
  hosts: clickhouse
  become: yes
  roles:
      - role: clickhouse-server
  vars:
      rpm_extra_packages:
          - net-tools
          - vim
  tasks:
      - include_tasks: roles/clickhouse-server/tasks/clickhouse-install.yml
  handlers:
      - name: Regenerate GRUB on RedHat
        shell: grub2-mkconfig -o /boot/grub2/grub.cfg
        when: ansible_facts['os_family'] == "RedHat"
      - name: Regenerate GRUB on Debian
        shell: update-grub
        when: ansible_facts['os_family'] == "Debian"

      - name: restart ch
        systemd:
            name: clickhouse-server.service
            state: restarted
