---
- name: Ensure clickhouse group exists
  group:
      name: clickhouse
      state: present

- name: Ensure clickhouse user exists
  user:
      name: clickhouse
      group: clickhouse
      home: /nonexistent
      shell: /usr/sbin/nologin
      state: present

- name: Install additional packages deb
  apt:
      name: "{{ deb_extra_packages }}"
  when: ansible_facts['os_family'] == "Debian"

- name: Install additional packages rpm
  yum:
      name: "{{ rpm_extra_packages }}"
  when: ansible_facts['os_family'] == "RedHat"

- name: apt add CH repo
  shell: |
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754
      echo "deb https://packages.clickhouse.com/deb stable main" | sudo tee /etc/apt/sources.list.d/clickhouse.list
      apt-get update
  when: ansible_facts['os_family'] == "Debian"

- name: yum add CH repo
  shell: |
      yum-config-manager --add-repo https://packages.clickhouse.com/rpm/clickhouse.repo
  when: ansible_facts['os_family'] == "RedHat"

- name: Install CH package deb
  apt:
      name: "{{ item }}"
  when: ansible_facts['os_family'] == "Debian"
  loop:
      - clickhouse-keeper

- name: Install CH package rpm
  yum:
      name: "{{ item }}"
  when: ansible_facts['os_family'] == "RedHat"
  loop:
      - clickhouse-keeper

- name: Enable delay accounting
  sysctl:
      name: kernel.task_delayacct
      value: 1
      state: present
      reload: yes

- name: Ensure delay accounting is enabled on boot
  lineinfile:
      path: /etc/sysctl.conf
      line: "kernel.task_delayacct=1"
      state: present

- name: Ensure transparent hugepages are set to never in GRUB_CMDLINE_LINUX
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=".*?)(\s*transparent_hugepage=never)?(")$'
    replace: '\1 transparent_hugepage=never\3'
  when: ansible_facts['os_family'] == "RedHat"
  notify: Regenerate GRUB configuration

- name: Ensure transparent hugepages are set to never in GRUB_CMDLINE_LINUX
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=".*?)(\s*transparent_hugepage=never)?(")$'
    replace: '\1 transparent_hugepage=never\3'
  when: ansible_facts['os_family'] == "Debian"
  notify: Regenerate GRUB configuration

- name: Create CH data dir
  file:
      path: "{{ item }}"
      state: directory
      owner: clickhouse
      group: clickhouse
      mode: "0750"
  loop:
      - /data

- name: Create CH keeper dirs
  file:
      path: "{{ item }}"
      state: directory
      owner: clickhouse
      group: clickhouse
      mode: "0750"
  loop:
      - /etc/clickhouse-keeper
      - /etc/clickhouse-keeper/config.d
      - /var/lib/clickhouse
      - /var/lib/clickhouse/tmp
      - /var/lib/clickhouse/data
      - /var/lib/clickhouse/metadata
      - /var/log/clickhouse-keeper

- name: Copy CH config.xml config file
  copy:
      src: roles/clickhouse-keeper/files/config.xml
      dest: /etc/clickhouse-keeper/config.xml
      owner: clickhouse
      group: clickhouse
      mode: "0644"
  notify: "restart ch keeper"

- name: Copy CH keeper.xml config file
  template:
      src: roles/clickhouse-keeper/templates/keeper.xml.j2
      dest: /etc/clickhouse-keeper/config.d/config.xml
      owner: clickhouse
      group: clickhouse
      mode: "0644"
  notify: "restart ch keeper"

- name: Copy ClickHouse Keeper systemd file
  copy:
      src: roles/clickhouse-keeper/files/clickhouse-keeper.service
      dest: /etc/systemd/system/clickhouse-keeper.service
      owner: root
      group: root
      mode: "0644"

- name: Reload systemd
  systemd:
      daemon_reload: yes

- name: Enable ClickHouse Keeper service
  systemd:
      name: clickhouse-keeper
      enabled: yes

- name: Start ClickHouse Keeper service
  systemd:
      name: clickhouse-keeper
      state: started
