galaxy_info:
  author: Man_from_Nocturne
  description: ClickHouse DB ansible role
  company: mtt

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1

  galaxy_tags: [ch,clickhouse]
dependencies: []

