---
- name: Install additional packages deb
  apt:
      name: '{{ deb_extra_packages + ["apt-transport-https"] }}'
  when: ansible_facts['os_family'] == "Debian"

- name: Install additional packages rpm
  yum:
      name: '{{ rpm_extra_packages + ["yum-utils"] }}'
  when: ansible_facts['os_family'] == "RedHat"

- name: apt add CH repo
  shell: |
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754
      echo "deb https://packages.clickhouse.com/deb stable main" | sudo tee /etc/apt/sources.list.d/clickhouse.list
      apt-get update
  when: ansible_facts['os_family'] == "Debian"

- name: yum add CH repo
  shell: |
      yum-config-manager --add-repo https://packages.clickhouse.com/rpm/clickhouse.repo
  when: ansible_facts['os_family'] == "RedHat"

- name: Install CH package deb
  apt:
      name: "{{ item }}"
  when: ansible_facts['os_family'] == "Debian"
  loop:
      - clickhouse-server
      - clickhouse-client

- name: Install CH package rpm
  yum:
      name: "{{ item }}"
  when: ansible_facts['os_family'] == "RedHat"
  loop:
      - clickhouse-server
      - clickhouse-client

- name: Enable delay accounting
  sysctl:
      name: kernel.task_delayacct
      value: 1
      state: present
      reload: yes

- name: Ensure delay accounting is enabled on boot
  lineinfile:
      path: /etc/sysctl.conf
      line: "kernel.task_delayacct=1"
      state: present

- name: Ensure transparent hugepages are set to never in GRUB_CMDLINE_LINUX
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=".*?)(\s*transparent_hugepage=never)?(")$'
    replace: '\1 transparent_hugepage=never\3'
  when: ansible_facts['os_family'] == "RedHat"
  notify: Regenerate GRUB configuration

- name: Ensure transparent hugepages are set to never in GRUB_CMDLINE_LINUX
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=".*?)(\s*transparent_hugepage=never)?(")$'
    replace: '\1 transparent_hugepage=never\3'
  when: ansible_facts['os_family'] == "Debian"
  notify: Regenerate GRUB configuration

- name: Create CH data dir
  file:
      path: "{{ item }}"
      state: directory
      owner: clickhouse
      group: clickhouse
      mode: "0750"
  loop:
      - /data
      - /data/clickhouse
      - /data/clickhouse/format_schemas
      - /data/clickhouse/user_files
      - /data/clickhouse/access
      - /data/clickhouse/tmp

- name: Create CH log dir
  file:
      path: "{{ item }}"
      state: directory
      owner: clickhouse
      group: clickhouse
      mode: "0770"
  loop:
      - /var/log/clickhouse-server

- name: Create CH config dir
  file:
      path: "{{ item }}"
      state: directory
      owner: clickhouse
      group: clickhouse
      mode: "0750"
  loop:
      - /etc/clickhouse-server
      - /etc/clickhouse-server/config.d
      - /etc/clickhouse-server/users.d

# - name: Copy CH config.xml config file
#   copy:
#     src: roles/clickhouse/files/config.xml
#     dest: /etc/clickhouse-server/config.xml
#     owner: clickhouse
#     group: clickhouse
#     mode: '0644'
#   notify: restart ch

- name: Deploy CH config.xml config file
  template:
      src: roles/clickhouse-server/templates/config.xml.j2
      dest: /etc/clickhouse-server/config.xml
      owner: clickhouse
      group: clickhouse
      mode: "0644"
  notify: restart ch

- name: Copy CH users.xml config file
  template:
      src: roles/clickhouse-server/templates/users.xml.j2
      dest: /etc/clickhouse-server/users.xml
      owner: clickhouse
      group: clickhouse
      mode: "0644"
  notify: restart ch

- name: Copy CH extra_users.xml config file
  template:
      src: roles/clickhouse-server/templates/extra_users.xml.j2
      dest: /etc/clickhouse-server/users.d/users.xml
      owner: clickhouse
      group: clickhouse
      mode: "0644"
  notify: restart ch

- name: Copy CH cluster.xml config file
  template:
      src: roles/clickhouse-server/templates/cluster.xml.j2
      dest: /etc/clickhouse-server/config.d/cluster.xml
      owner: clickhouse
      group: clickhouse
      mode: "0644"
  notify: restart ch

- name: Copy CH macros.xml config file
  template:
      src: roles/clickhouse-server/templates/macros.xml.j2
      dest: /etc/clickhouse-server/config.d/macros.xml
      owner: clickhouse
      group: clickhouse
      mode: "0644"
  notify: restart ch

- name: Copy CH zookeeper.xml config file
  template:
      src: roles/clickhouse-server/templates/keeper.xml.j2
      dest: /etc/clickhouse-server/config.d/keeper.xml
      owner: clickhouse
      group: clickhouse
      mode: "0644"
  notify: restart ch

- name: Copy CH system_logs.xml config file
  template:
      src: roles/clickhouse-server/templates/system_logs.j2
      dest: /etc/clickhouse-server/config.d/system_logs.xml
      owner: clickhouse
      group: clickhouse
      mode: "0644"
  notify: restart ch

- name: start clickhouse-server.service
  systemd:
      name: clickhouse-server.service
      state: started
      enabled: yes
